training_data = [
    ("The quick brown fox jumps", 0),
    ("over the lazy dog", 1),
    ("Once upon a time", 0),
    ("in a land far away", 0),
    ("there was a princess", 0),
    ("who lived in a castle", 1),
    ("with her parents and two sisters", 1),
    ("The sun was setting behind the mountains", 0),
    ("and the sky was a beautiful shade of pink", 0),
    ("She looked out the window and saw", 0),
    ("a bird perched on a tree branch", 0),
    ("The wind was blowing strongly that day", 0),
    ("and the leaves rustled in the breeze", 0),
    ("The old man sat on the park bench", 0),
    ("feeding the pigeons with breadcrumbs", 0),
    ("The concert was sold out", 1),
    ("and the crowd was buzzing with excitement", 1),
    ("The stage lights flickered on", 1),
    ("and the band started playing their first song", 1),
    ("The train chugged along the tracks", 0),
    ("and the passengers settled in for the long ride", 0),
    ("The plane took off smoothly", 1),
    ("and the passengers felt the rush of acceleration", 1),
    ("The children played in the park", 0),
    ("laughing and chasing each other", 0),
    ("The sun set slowly over the horizon", 0),
    ("casting a warm glow over the city", 0),
    ("The storm raged outside", 0),
    ("as the family huddled together inside", 0),
    ("The phone rang loudly in the middle of the night", 0),
    ("jolting her awake from a deep sleep", 0),
    ("The door creaked open slowly", 0),
    ("revealing a dark and ominous room", 0),
    ("The cake smelled delicious", 0),
    ("and she couldn't wait to take a bite", 0),
    ("The smell of fresh coffee filled the air", 0),
    ("as she sat down to start her day", 0),
    ("The book was a thrilling adventure", 0),
    ("that kept her on the edge of her seat", 0),
    ("The painting was a masterpiece", 0),
    ("that captured the essence of the human experience", 0),
    ("The mountain loomed ahead of them", 0),
    ("majestic and awe-inspiring", 0),
    ("The river flowed gently by", 0),
    ("its tranquil waters reflecting the blue sky", 0),
    ("The city was a bustling metropolis", 0),
    ("full of life and energy", 0),
    ("The forest was a peaceful retreat", 0),
    ("where she could escape from the world", 0),
    ("The beach was a paradise", 0),
    ("with its white sands and crystal-clear waters", 0),
    ("The snow was falling softly", 0),
    ("covering everything in a blanket of white", 0),
    ("He wanted to go to", 0),
    ("the store to buy some milk", 1),
    ("I was walking down the street", 0),
    ("when I saw a bird fly by", 1),
    ("The sun was shining brightly", 0),
    ("and the sky was a brilliant blue", 1),
    ("Mary had a little lamb", 0),
    ("whose fleece was white as snow", 1),
    ("Peter Piper picked a peck of pickled peppers", 0),
    ("A peck of pickled peppers Peter Piper picked", 1),
    ("She sells seashells by the seashore", 0),
    ("The shells she sells are surely seashells", 1),
    ("Betty Botter bought some butter", 0),
    ("But she said the butter's bitter", 1),
    ("How much wood would a woodchuck chuck", 0),
    ("if a woodchuck could chuck wood", 1),
    ("How can a clam cram in a clean cream can", 0),
    ("A clam can cram in a clean cream can", 1),
    ("The quick brown fox jumps", 0),
    ("over the lazy dog", 1),
    ("Once upon a time", 0),
    ("in a land far away", 0),
    ("there was a princess", 0),
    ("who lived in a castle", 1),
    ("with her parents and two sisters", 1),
    ("I woke up early this morning", 1),
    ("to watch the sunrise", 1),
    ("but it was too cloudy", 0),
    ("so I went back to bed", 1),
    ("My favorite food is pizza", 1),
    ("especially when it has lots of cheese", 1),
    ("but I don't like olives on it", 0),
    ("I have a big exam tomorrow", 0),
    ("and I'm feeling really nervous", 1),
    ("so I'm going to study all night", 1),
    ("My car broke down on the highway", 0),
    ("so I had to call a tow truck", 1),
    ("but it took over an hour to arrive", 0),
    ("I love going to the beach", 1),
    ("and playing in the ocean", 1),
    ("but I always forget to wear sunscreen", 0),
    ("My favorite hobby is reading", 1),
    ("especially mystery novels", 1),
    ("but I can't stand romance novels", 0),
    ("I went to the grocery store", 1),
    ("to buy some milk and bread", 1),
    ("but they were out of both", 0),
    ("My favorite movie is The Godfather", 1),
    ("because of its excellent acting and storytelling", 1),
    ("but I can't stand horror movies", 0),
    ("I love going for walks in the park", 1),
    ("especially during the fall when the leaves are changing colors", 1),
    ("but I hate going for walks in the rain", 0),
    ("I'm really excited for the concert tonight", 1),
    ("I've been waiting for it for months", 1),
    ("but I hope I don't get stuck in traffic on the way there", 0),
    ("I'm really enjoying this book", 1),
    ("it's so well-written and engaging", 1),
    ("but I don't like the main character very much", 0),
    ("I'm planning a trip to Europe next summer", 1),
    ("I want to visit Paris and Rome", 1),
    ("but I'm worried about the cost", 0),
    ("I'm having a great time at this party", 1),
    ("the music is really good and the people are friendly", 1),
    ("but I'm getting tired and I have work in the morning", 0),
    ("I'm really excited to start my new job", 1),
    ("it's a great opportunity with a lot of room for growth", 1),
    ("but I'm nervous about meeting all of my new coworkers", 0),
    ("I'm not feeling very well today", 0),
    ("I think I might have caught a cold", 1),
    ("so I'm going to stay home and rest", 1),
    ("I'm a big fan of Taylor Swift", 1),
    ("her music is so catchy and upbeat", 1),
    ("but I can't stand heavy metal music", 0),
    ("I'm really looking forward to the weekend", 1),
    ("The weather is supposed to be nice", 1),
    ("The cat sleeps on the couch", 1),
    ("The dog barks at the mailman", 1),
    ("The sun rises in the east", 1),
    ("The moon shines in the night sky", 1),
    ("The leaves rustle in the wind", 1),
    ("The flowers bloom in the spring", 1),
    ("The rain falls from the sky", 1),
    ("The snow covers the ground", 1),
    ("The stars twinkle in the night", 1),
    ("The waves crash against the shore", 1),
    ("The bird sings a sweet melody", 1),
    ("The plane soars through the clouds", 1),
    ("The train chugs down the tracks", 1),
    ("The car zooms down the highway", 1),
    ("The boat floats on the water", 1),
    ("The fish swim in the ocean", 1),
    ("The butterfly flutters its wings", 1),
    ("The bee buzzes from flower to flower", 1),
    ("The ant crawls across the ground", 1),
    ("The spider spins its web", 1),
    ("The bear roams through the forest", 1),
    ("The lion hunts for its prey", 1),
    ("The tiger prowls through the jungle", 1),
    ("The elephant trumpets loudly", 1),
    ("The giraffe towers above the trees", 1),
    ("The monkey swings from branch to branch", 1),
    ("The snake slithers through the grass", 1),
    ("The alligator lurks in the water", 1),
    ("The hippo wallows in the mud", 1),
    ("The rhino charges through the savannah", 1),
    ("The whale breaches the surface of the water", 1),
    ("The dolphin jumps out of the waves", 1),
    ("The octopus squirts ink when threatened", 1),
    ("The crab scuttles sideways on the beach", 1),
    ("The seagull flies overhead, searching for food", 1),
    ("The pelican dives into the water for fish", 1),
    ("The eagle soars high above the mountains", 1),
    ("The hawk swoops down to catch its prey", 1),
    ("The owl hoots in the night", 1),
    ("The peacock displays its beautiful feathers", 1),
    ("The flamingo stands on one leg", 1),
    ("The penguin waddles across the ice", 1),
    ("The sloth moves slowly through the trees", 1),
    ("The koala sleeps in the eucalyptus tree", 1),
    ("The kangaroo hops across the outback", 1),
    ("The emu runs across the desert", 1),
    ("The camel walks across the sand dunes", 1),
    ("The deer runs through the forest", 1),
    ("The fox dashes through the field", 1),
    ("The wolf howls at the moon", 1),
    ("The coyote prowls through the desert", 1),
    ("The raccoon scavenges for food", 1),
    ("The skunk sprays a foul odor when threatened", 1),
    ("The opossum plays dead to avoid danger", 1),
    ("The beaver builds a dam in the river", 1),
    ("The squirrel gathers nuts for the winter", 1),
    ("The chipmunk scurries across the ground", 1),
    ("The rabbit hops through the meadow", 1),
    ("The hedgehog curls up into a ball for protection", 1),
    ("The porcupine quills are sharp and dangerous", 1),
    ("The goat eats grass on the mountainside", 1),
    ("The sheep graze in the pasture", 1),
    ("The cow gives milk to her calf", 1),
    ("The pig rolls in the mud to cool off", 1),
    ("The horse gallops across the field", 1),
    ("The donkey brays loudly", 1),
    ("The chicken lays an egg in the coop", 1),
    ("The rooster crows to wake up the farm", 1),
    ("The turkey is the main course on Thanksgiving", 1),
    ("The beekeeper collects honey from the hive", 1),
    ("The gardener tends to the plants in the greenhouse", 1),
    ("Despite her best efforts,", 0),
    ("Running through the park,", 0),
    ("After hours of studying", 0),
    ("In the middle of the night", 0),
    ("Looking out the window", 0),
    ("Without a second thought", 0),
    ("With a heavy heart", 0),
    ("Holding onto her phone tightly", 0),
    ("Walking down the street", 0),
    ("Waiting for the train", 0),
    ("Despite the heavy rain and wind all night long", 0),
    ("Eating breakfast, enjoying the view from the balcony", 0),
    ("Playing video games with my friends, winning every match", 0),
    ("With a broken leg and a cast on my arm, it was impossible to drive", 0),
    ("In the middle of the street, honking and shouting at each other", 0),
    ("Sitting in the park, watching the birds and squirrels", 0),
    ("After waiting for hours in the queue, finally reaching the front of the line", 0),
    ("During the storm, the power went out and we were left in the dark", 0),
    ("On the top of the mountain, looking at the breathtaking scenery", 0),
    ("Without any warning, the car suddenly broke down on the highway", 0),
    ("The students were excited for the field trip to the zoo, and they were hoping to see some of their favorite animals like lions, giraffes, and elephants", 1),
    ("Mary went to the store to buy groceries, and she picked up some milk, bread, eggs, and vegetables", 1),
    ("The weather was beautiful, with blue skies and a gentle breeze blowing through the trees, making it the perfect day for a picnic", 1),
    ("John loves to read books, especially ones about history and science, and he spends most of his free time at the library", 1),
    ("The restaurant was packed with customers, and the waitstaff were struggling to keep up with all the orders, but they managed to serve everyone in a timely manner", 1),
    ("The sun sets in the west", 1),
    ("She is a talented musician who plays several instruments", 1),
    ("They went to the store to buy groceries and ended up buying more than they planned", 1),
    ("The dog barked loudly at the mailman, who quickly walked away", 1),
    ("I have a doctor's appointment at 2 PM tomorrow", 1),
    ("The movie was long and boring, but the ending was surprising", 1),
    ("The cat curled up on the couch and slept for hours", 1),
    ("My favorite color is blue, but I also like green and purple", 1),
    ("The restaurant was crowded, so they decided to eat somewhere else", 1),
    ("He woke up early and went for a run before work", 1),
    ("Running late for the meeting", 0),
    ("Without his keys, he couldn't enter the building", 0),
    ("Eating dinner with friends at the new restaurant in town", 0),
    ("Waiting for the train to arrive at the station", 0),
    ("With a loud noise coming from the engine", 0),
    ("Walking through the park on a sunny day", 0),
    ("Forgot to turn off the stove before leaving the house", 0),
    ("Watching the movie without any subtitles", 0),
    ("Lost in thought about what to do next", 0),
    ("Biking on the trail through the woods", 0),
    ("The sun sets in the west", 1),
    ("She is a talented musician who plays several instruments", 1),
    ("They went to the store to buy groceries and ended up buying more than they planned", 1),
    ("The dog barked loudly at the mailman, who quickly walked away", 1),
    ("I have a doctor's appointment at 2 PM tomorrow", 1),
    ("The movie was long and boring, but the ending was surprising", 1),
    ("The cat curled up on the couch and slept for hours", 1),
    ("My favorite color is blue, but I also like green and purple", 1),
    ("The restaurant was crowded, so they decided to eat somewhere else", 1),
    ("He woke up early and went for a run before work", 1),
    ("Despite studying for hours every day", 0),
    ("Running through the park in the morning", 0),
    ("Waking up early to catch the sunrise", 0),
    ("Having a great time with my friends at the party", 0),
    ("Looking forward to going on vacation next month", 0),
    ("While walking down the street on a sunny day", 0),
    ("Trying my best to learn a new language", 0),
    ("Eating a delicious meal at my favorite restaurant", 0),
    ("Waiting for the train to arrive at the station", 0),
    ("Listening to music and singing along with the lyrics", 0),
]
